### ISSUE TITLE
TypeError: mime.lookup is not a function while upgrading mime version 

### ISSUE THREAD

**Issue by guptas89** [pillarjs/send#210]
Hi,

I am getting one of the security issues i.e. https://github.com/advisories/GHSA-wrvr-8mpx-r7pp in [mime](https://www.npmjs.com/package/mime). When upgrading mime to 2.X.X then I am getting the below error in send.js:

var type = mime.lookup(path)
                  ^
TypeError: mime.lookup is not a function
    at SendStream.type (..\node_modules\send\index.js:838:19)

Mime version in package.json file should be upgraded to >=2.X.X or latest one

Readme for mime 2.X.X  => https://www.npmjs.com/package/mime/v/2.0.5#version-2-notes

**Comment by dougwilson** [comment]
Duplicate of #200

The included mime 1.6.0 is not affected by the security issue you linked, either. The affected verion ranges are listed on the page you link. In the 1.x branch, only versions below 1.4.1 are affected.
